### PR TITLE
SCMOD-6665: Add locale, update tini

### PR DESCRIPTION
**Pull request by rob-duewer**
Add explicit locale setting (locale constrcuted in opensuse/leap, but not properly set)
Update copyright
Update to current tini version.  (was from 2017, current is apr. 2018)

Basic testing against raw dockerfile for successful build and handling of files with foreign characters.

### CODE REVIEW

**Comment by dermot-hardy** [comment]
Don't worry about it this time but for future reference unrelated changes should not be submitted together in one PR.  An issue with any of them will prevent all from being merged.

https://github.com/salemove/github-review-helper/blob/master/doc/rules.md#focused

**Comment by dermot-hardy** [comment]
I've created a developer build for this:
http://sou-jenkins2.hpeswlab.net/job/CAFapi/job/CAFapi~opensuse-base-image~scmod-6665_locale_tini_cpright~CI/

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
The developer build has failed.  It looks like an issue with the copyright header:

    [ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (check-license-headers) on project opensuse-base-image: Some files do not have the expected license header -> [Help 1]

**Comment by dermot-hardy** [comment]
I corrected the copyright header changes (see [here](https://github.com/CAFapi/opensuse-base-image/commit/29991c1bd7ea97b6f0eb45092ecd19b489dfd570)) and it's building ok now so we have an image we can test (i.e. `cafinternal/prereleases:opensuse-base-1.3.0-scmod-6665_locale_tini_cpright-SNAPSHOT`).

Is there a simple way to demonstrate the effect of the locale change?

**Comment by rob-duewer** [comment]
1. Ok, I will make sure to separate the commits to do different things (which if I am reading that properly is what that particular person is guiding to.)  It seems utterly silly to do three separate PR's for this (given the minimal changes in each), but I certainly agree to segmenting them to different commit ID's.  BTW, if this is the desired standard for all our MF opensource projects, do you want to bring portions of that doc into a cafapi repo instead of just linking to a guidance doc owned by glia.com?

2. Thanks for running down all the copyright locations across everything in the project (beyond just the file I was operating on).  I forgot we had a checker during build for them, so that is very handy.

3. Sure thing on testing.  Two things to do.  Easiest way is to simply launch a copy of the container (original if you want to see what was broken before) and just bash as your endpoint. 
a. issue the locale command.  If it isn't set, it will look like this:
f60e6a5d527a:/ # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

If it is, it will look like this:
e04ab2d11045:/ # locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

b. Next to see the actual effects.  Go grab a high code character and touch a file using it as the name.  (IE Ϣ.txt).  Now do a ls where you wrote it.  If the locale isn't set, you'll get back something that looks like this:
-rw-r--r--.   1 root root     0 Sep 17 13:55 ''$'\317\242''.txt'

On a system where the locale is properly set, it'll look like this:
-rw-r--r--.   1 root root     0 Sep 17 13:58 Ϣ.txt

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
